### ISSUE TITLE
Make job deletion configurable

### ISSUE THREAD

**Issue by saurabhnanda** [saurabhnanda/odd-jobs#104]
Currently there are only two options here:

- `cfgDeleteSuccessfulJobs`: `True` or `False`

I propose something like the following:

```haskell
data Config = Config
  { -- | This function will be evaluated every time a job is attempted (at the __end__ of the attempt)
   cfgImmediateJobDeletion :: Job -> IO Bool 

   -- | Another polling thread will be setup to run every 'cfgPollingInterval' seconds to execute this query
  , cfgDelayedJobDeletionSql :: PGS.Query
  , ...
  } 

defaultImmediateJobDeletion :: Job -> IO Bool
defaultImmedateJobDeletion Job{jobStatus} = 
  pure $ jobStatus == Success

defaultDeleayedJobDeletionSql :: PGS.Query
defaultDeleayedJobDeletionSql = 
  "DELETE FROM jobs WHERE status in ('success', 'failed') AND run_at < current_timestamp - '7 days'::interval"
```

## Use cases

- cleanup of failed jobs after enough time has passed (this is the same as #22)
-  delay a job's deletion for cases where an ephemeral [job result](#103)
- make job deletion logic highly configurable (useful for advanced use-cases like "workflows" -- coming up in a future PR)

**Comment by saurabhnanda** [comment]
Folks, if anyone has a strong objection to the above proposal, please let me know. 

@ivb-supercede @tfausak @jappeace @tchoutri 

Please tag any other active users of odd-jobs as well.

**Comment by tchoutri** [comment]
LGTM :+1:

**Comment by jappeace** [comment]
would be nice this could be changed without breaking existing code

**Comment by saurabhnanda** [comment]
@jappeace if the fields of `Config` are changed but  the type-signature of `OddJobs.ConfigBuilder.mkConfig` is maintained, even , would that work for you?

cc: @tfausak
