### ISSUE TITLE
Some job callbacks are not used

### ISSUE THREAD

**Issue by tfausak** [saurabhnanda/odd-jobs#63]
The config has a few callbacks for job lifecycle events:

- `cfgOnJobStart`
- `cfgOnJobSuccess`
- `cfgOnJobFailed`
- `cfgOnJobTimeout`

Of those, `cfgOnJobSuccess` and `cfgOnJobFailed` appear to be called correctly. As far as I can tell the other two, `cfgOnJobStart` and `cfgOnJobTimeout`, are never used.

`cfgOnJobStart` is wired into the `onJobStart` method of the `HasJobRunner` class for `RunnerM`, but `onJobStart` itself is never called. 

`cfgOnJobTimeout` appears to be completely unused.

**Comment by saurabhnanda** [comment]
@tfausak I've got #68  now to fix this issue. But I've not decided whether both, `onJobFailed` and `onJobTimeout`, are required or only `onJobFailed` is good-enough (with `TimeoutException` being treated as just another reason for failure). Any thoughts?

**Comment by tfausak** [comment]
I'd be fine with combining both the "failed" and "timeout" callbacks into one.
