### ISSUE TITLE
Odd jobs create table fails with exception if table already exists.

### ISSUE THREAD

**Issue by shawn-bachlet** [saurabhnanda/odd-jobs#66]
Using `CREATE TABLE IF NOT EXISTS` here https://github.com/saurabhnanda/odd-jobs/blob/0236697e649053f3f36271000cdeb247e2295d58/src/OddJobs/Migrations.hs#L13 instead of `CREATE TABLE` will stop this function from failing if the table already exists.

**Comment by saurabhnanda** [comment]
@shawn-bachlet fixed on the `master` branch.
